FROM tiangolo/meinheld-gunicorn-flask:python3.7

COPY ./app /app
COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

ENV AWS_COGNITO_CLIENT_ID $AWS_COGNITO_CLIENT_ID
ENV AWS_COGNITO_POOL_ID $AWS_COGNITO_POOL_ID
ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION
ENV AWS_IAM_ACCESS_KEY $AWS_IAM_ACCESS_KEY
ENV AWS_IAM_SECRET_KEY $AWS_IAM_SECRET_KEY
ENV DB_DB $DB_DB
ENV DB_HOST $DB_HOST
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_USER $DB_USER
ENV FLASK_SECRET_KEY $FLASK_SECRET_KEY
